# Generated by Django 3.1.5 on 2021-01-11 02:50

import cms.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=256, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('headline', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок текста главной страницы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Долгота')),
                ('photo_width', models.PositiveIntegerField(blank=True, default=1240, null=True, verbose_name='Ширина фото слайдера')),
                ('photo_height', models.PositiveIntegerField(blank=True, default=833, null=True, verbose_name='Высота фото слайдера')),
            ],
            options={
                'verbose_name': 'Главная страница сайта',
                'verbose_name_plural': 'Редактирование главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок списка опций')),
            ],
            options={
                'verbose_name': 'Заголовок списка опций',
                'verbose_name_plural': 'Заголовки списков опций',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=256, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название продукта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', validators=[cms.models.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])], verbose_name='Фотография продукта')),
                ('photo_width', models.PositiveIntegerField(blank=True, default=1240, null=True, verbose_name='Ширина фотографии')),
                ('photo_height', models.PositiveIntegerField(blank=True, default=992, null=True, verbose_name='Высота фотографии')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Редактирование продуктов',
            },
        ),
        migrations.CreateModel(
            name='Suboption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Пункт списка')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.option', verbose_name='Опции')),
            ],
            options={
                'verbose_name': 'Пункт списка',
                'verbose_name_plural': 'Пункты списка',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/', validators=[cms.models.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])], verbose_name='Фотография слайдера главной страницы')),
                ('name', models.CharField(max_length=256, verbose_name='Название фотографии')),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.indexpage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.indexpage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Абзац',
                'verbose_name_plural': 'Абзацы',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.product', verbose_name='Продукт'),
        ),
    ]
