# Generated by Django 3.1.5 on 2021-01-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=130, unique=True, verbose_name='Ссылка'),
        ),
    ]
